language: csharp
solution: ./C#/SolarLunarName.sln
install:
  - nuget restore ./C#/SolarLunarName.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./C#/SolarLunarName/SolarLunarName.Standard.Tests 
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./bin/Release/SolarLunarName.Standard.Tests.dll
