language: csharp
mono: none
dotnet: 3.0

install:
  - dotnet tool install -g coveralls.net --version 1.0.0
  - dotnet restore ./src/SolarLunarName/SolarLunarName.Standard.Tests/SolarLunarName.Standard.Tests.csproj
script:
  - cd ./src/SolarLunarName
  - dotnet tool restore 
  - dotnet paket restore
  - source ../../CreateTestCoverage.sh